### ISSUE TITLE
Default process group has not been initialized

### ISSUE THREAD

**Issue by Dream-swift** [NiccoloCavagnero/PEM#10]
my gpu is 3070m with windows. When start train  it show RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.
I use the row from README : `python train_net.py --num-gpus 0 --config-file configs/cityscapes/semantic-segmentation/pem_R50_bs32_90k.yaml``` 
So how can I solute this?
![image](https://github.com/user-attachments/assets/e9ce3b52-50c4-4262-b082-1d11ac8b2d70)

**Comment by NiccoloCavagnero** [comment]
We have never tested the code on Windows, nonetheless I think you should specify "--num-gpus 1" if you have a single GPU.

**Comment by Dream-swift** [comment]
> We have never tested the code on Windows, nonetheless I think you should specify "--num-gpus 1" if you have a single GPU.

I try use "--num-gpus 1" but still output this mistake

**Comment by NiccoloCavagnero** [comment]
Possibly, this issue is related to the use of SyncBatchNorm which expect multiple GPUs. You can try to convert all SyncBatchNorm layers to standard BatchNorm and it should work. 

You have an option to do so in the configuration files, but SyncBatchNorm is actually hardcoded in the Transformer Decoder so you have to manually change those.

**Comment by Dream-swift** [comment]
> Possibly, this issue is related to the use of SyncBatchNorm which expect multiple GPUs. You can try to convert all SyncBatchNorm layers to standard BatchNorm and it should work.
> 
> You have an option to do so in the configuration files, but SyncBatchNorm is actually hardcoded in the Transformer Decoder so you have to manually change those.

Thank you! I change all places where `SyncBatchNorm` appears, and now I can continue
