### ISSUE TITLE
How to determine the required parameters for defining MultiScaleMaskedTransformerDecoder?

### ISSUE THREAD

**Issue by zzzyzh** [NiccoloCavagnero/PEM#12]

**Comment by zzzyzh** [comment]
https://github.com/NiccoloCavagnero/PEM/blob/ed8baf5e3dcaaa526672b3fcbf7c788256522c07/pem/modeling/transformer_decoder/pem_transformer_decoder.py#L285

I am currently trying to work with the `MultiScaleMaskedTransformerDecoder` class in your repository. However, I'm having difficulty determining the necessary parameters required to define this class.

Could you please provide guidance on:

1. What are the required parameters for initializing the `MultiScaleMaskedTransformerDecoder`?
2. Are there any specific references or examples in the codebase that I can refer to for setting up this class correctly?

**Comment by NiccoloCavagnero** [comment]
You can find all hyper-parameters in the configuration files.
You can check the function "from_config()" within MultiScaleMaskedTransformerDecoder to check how the configuration files are mapped to the class hyper-parameters.
