### ISSUE TITLE
Handling argmax in PEM-CA Module

### ISSUE THREAD

**Issue by zzzyzh** [NiccoloCavagnero/PEM#13]
I noticed that in the **PEM-CA** module, you mentioned using the `argmax` operation. As far as I understand, using `argmax` could potentially lead to issues with gradient backpropagation, since it is a non-differentiable operation.

Could you please explain how you have managed to avoid or mitigate this issue in your implementation?

**Comment by NiccoloCavagnero** [comment]
Happy that you are really delving deep in our codebase!

This is an interesting question, you are right and indeed argmax is not differentiable. Indeed, gradient is only backpropagated through prototypes tokens, i.e. the selection mechanism is not supervised, it comes for free from the segmentation head where you are trying to maximise the dot product between features and queries. 

In practice, to get the prediction you perform a dot product between features and queries. This means that the whole architecture is been trained to maximise the dot product among instance features and their corresponding queries. Therefore, you do not need to specifically supervise the selection mechanism, as the network itself is already aligning instance features and queries.

If you need the gradient to be propagated through each feature token, you can follow this approach:
- in place of assigning a single feature token to each query, you assign a query to each token (i.e. you simply change the dimension where the argmax is applied);
- considering the assigned queries as cluster labels, take the average token for a specific query.
This way, in place of taking the most similar token with respect to each query, you consider the average token and you will have gradient for each feature token.

We also tested this configuration, but it does not bring any advantage in terms of performance.
