### ISSUE TITLE
How to calculate loss and generate pred_masks.

### ISSUE THREAD

**Issue by zzzyzh** [NiccoloCavagnero/PEM#14]
https://github.com/NiccoloCavagnero/PEM/blob/ed8baf5e3dcaaa526672b3fcbf7c788256522c07/pem/modeling/transformer_decoder/pem_transformer_decoder.py#L499

I have a question regarding the `pred_masks` output in PEM. We know that `num_query = 100`, and the channel dimension of `pred_masks` is equal to `num_query`. This is different from the typical segmentation output where we would expect the number of channels to match the number of classes.

Could you please explain how the loss is calculated using `pred_masks` in this case? Additionally, how should we generate the final segmentation result from `pred_masks`?

**Comment by NiccoloCavagnero** [comment]
Please, refer to Mask2Former for loss computation and other training details.
