### ISSUE TITLE
change this backbone to swin

### ISSUE THREAD

**Issue by zxqing01** [NiccoloCavagnero/PEM#15]
Can I change this backbone to swin, because I found that stdc and r50 have a certain upper limit impact, if I change to swin, will it affect the effect, and what other parts do i need to modify?

**Comment by Gabrysse** [comment]
Hi @z2587721154. To use the swin backbone, you need to:

1. Implement the swin backbone and place it in the `pem/modelling/backbone/`.
2. Add the appropriate configuration files

For both points you can use the Mask2Former repo ([link](https://github.com/facebookresearch/Mask2Former)). There you can find what you have to add to the configuration files and you can just copy and paste the `swin.py` file.
