### ISSUE TITLE
ValueError: Cannot find 'sem_seg_file_name' for semantic segmentation dataset

### ISSUE THREAD

**Issue by Run-19** [NiccoloCavagnero/PEM#2]
Hello author, I am very interested in your paper and would like to conduct experiments on the code. I converted the polygon annotations of labelme to Coco format, registered and ran the code in train_net, but encountered the following error:
Raise Value Error（
Value Error: Cannot find 'sema_seg_filename' for semantic segmentation dataset/datasets/train2017/00000 1251. jpg
Python BaseException
I have run mask2Former and registered the dataset in the same way using training code, which can run it, but an error occurred on PEM. May I ask which step I made a mistake?
Thank You!!!

**Comment by Gabrysse** [comment]
Hi @Run-19, since we did not test the dataset you mentioned, can you provide me some additional information? 
For example:

- which scripts are you using for converting the annotations?
- which segmentation task are you trying to perform?

**Comment by ChaojunZ** [comment]
from detectron2.projects.deeplab import add_deeplab_config, build_lr_scheduler   error
AssertionError: Config file '' does not exist!

**Comment by Gabrysse** [comment]
Hi @ChaojunZ, can you please add more context to your issue? It is a bit hard to understand without additional details. Also, it might be better if you open another issue instead of using this one ;)

**Comment by ChaojunZ** [comment]
> 嗨，您能为您的问题添加更多上下文吗？如果没有其他细节，这有点难以理解。此外，如果您打开另一个问题而不是使用此问题可能会更好;)

hi, I'm very interested in your work.
I according to you provide the environment for the successful installation, but in train_net.py files line 47 from detectron2. projects. deeplab import add_deeplab_config, build_lr_scheduler. deeplab, add_deeplab_config, build_lr_scheduler were not found.

I run train_net.py and the following error occurs:
\pem-main\detectron2\detectron2\config\config.py", line 45, in merge_from_file
assert PathManager.isfile(cfg_filename), f"Config file '{cfg_filename}' does not exist!"
AssertionError: Config file '' does not exist!


Maybe there was an error in my running, but I couldn't fix it
![A](https://github.com/NiccoloCavagnero/PEM/assets/126930344/3304277c-9666-406a-9c88-0b36d514d038)

I am a beginner in this field and thank you very much for your reply and also for your outstanding work

**Comment by Gabrysse** [comment]
@ChaojunZ when you launch train_net.py you have to specify the configuration file.
As reported in the readme, to train our model you have to launch this command:

```
python train_net.py --num-gpus 4 \
  --config-file configs/cityscapes/semantic-segmentation/pem_R50_bs32_90k.yaml 
```

If you want to change the task or the dataset, chose the appropriate configuration file.

**Comment by dawang-11** [comment]
> Hello author, I am very interested in your paper and would like to conduct experiments on the code. I converted the polygon annotations of labelme to Coco format, registered and ran the code in train_net, but encountered the following error: Raise Value Error（ Value Error: Cannot find 'sema_seg_filename' for semantic segmentation dataset/datasets/train2017/00000 1251. jpg Python BaseException I have run mask2Former and registered the dataset in the same way using training code, which can run it, but an error occurred on PEM. May I ask which step I made a mistake? Thank You!!!

hello,i met the same problem when i run mask2former,can you share the training code used to register the dataset.thank you!!

**Comment by Gabrysse** [comment]
> > Hello author, I am very interested in your paper and would like to conduct experiments on the code. I converted the polygon annotations of labelme to Coco format, registered and ran the code in train_net, but encountered the following error: Raise Value Error（ Value Error: Cannot find 'sema_seg_filename' for semantic segmentation dataset/datasets/train2017/00000 1251. jpg Python BaseException I have run mask2Former and registered the dataset in the same way using training code, which can run it, but an error occurred on PEM. May I ask which step I made a mistake? Thank You!!!
> 
> hello,i met the same problem when i run mask2former,can you share the training code used to register the dataset.thank you!!

Hi @dawang-11. The training code and the dataset registration code are already included in the repository. Please refer to the readme file and the official detectron2 documentation.

**Comment by ShakespareSun** [comment]
> Hello author, I am very interested in your paper and would like to conduct experiments on the code. I converted the polygon annotations of labelme to Coco format, registered and ran the code in train_net, but encountered the following error: Raise Value Error（ Value Error: Cannot find 'sema_seg_filename' for semantic segmentation dataset/datasets/train2017/00000 1251. jpg Python BaseException I have run mask2Former and registered the dataset in the same way using training code, which can run it, but an error occurred on PEM. May I ask which step I made a mistake? Thank You!!!

May I ask if you have solved this problem? I also have the problem “Cannot find ‘sem_seg_file_name’ for semantic segmentation dataset” when registering my own dataset.   :(

**Comment by ShakespareSun** [comment]
> Hello author, I am very interested in your paper and would like to conduct experiments on the code. I converted the polygon annotations of labelme to Coco format, registered and ran the code in train_net, but encountered the following error: Raise Value Error（ Value Error: Cannot find 'sema_seg_filename' for semantic segmentation dataset/datasets/train2017/00000 1251. jpg Python BaseException I have run mask2Former and registered the dataset in the same way using training code, which can run it, but an error occurred on PEM. May I ask which step I made a mistake? Thank You!!!

May I ask if you have solved this problem? I also have the problem “Cannot find ‘sem_seg_file_name’ for semantic segmentation dataset” when registering my own dataset. :(   @Run-19

**Comment by Gabrysse** [comment]
Hi @ShakespareSun, since our codebase is based on Mask2Former and Detectron2, please refer to the official documentation for implementing a custom dataset [https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html).
