### ISSUE TITLE
dtype mismatch in Deform conv

### ISSUE THREAD

**Issue by abhishekaich27** [NiccoloCavagnero/PEM#3]
Hi @Gabrysse!

Why do you have this line here: https://github.com/NiccoloCavagnero/PEM/blob/42c3f652720edacc15e61d51e8c679879c5265ad/pem/modeling/pixel_decoder/pem_pixel_decoder.py#L127

It's causing an error in https://github.com/NiccoloCavagnero/PEM/blob/42c3f652720edacc15e61d51e8c679879c5265ad/pem/modeling/pixel_decoder/pem_pixel_decoder.py#L248 : 
![image](https://github.com/NiccoloCavagnero/PEM/assets/30926705/d3dec71a-ccb4-4719-aa83-0085fcae930c)

If I disable this line, I get a device-side trigger in the hungarian matching. Any inputs?

**Comment by Gabrysse** [comment]
Hi @abhishekaich27, this bug is caused by detectron itself. For this reason we asked in the readme to install detectron from our repository as we have made a change to fix the above issue.

**Comment by abhishekaich27** [comment]
Understood! Can you point to the change?

**Comment by Gabrysse** [comment]
Yes, of course.

https://github.com/NiccoloCavagnero/PEM/blob/main/detectron2/detectron2/layers/deform_conv.py#L221
https://github.com/NiccoloCavagnero/PEM/blob/main/detectron2/detectron2/layers/deform_conv.py#L251

**Comment by abhishekaich27** [comment]
Anyone trying to use their default detectron2 with PEM can add the following line after
[PEM/pem/modeling/pixel_decoder/pem_pixel_decoder.py](https://github.com/NiccoloCavagnero/PEM/blob/42c3f652720edacc15e61d51e8c679879c5265ad/pem/modeling/pixel_decoder/pem_pixel_decoder.py#L127)

Line 127 in [42c3f65](https://github.com/NiccoloCavagnero/PEM/commit/42c3f652720edacc15e61d51e8c679879c5265ad)

`x = self.dcn(out.to(self.dcn.weight.dtype), offset.to(self.dcn.weight.dtype), mask.to(self.dcn.weight.dtype))`

**Comment by Gabrysse** [comment]
Thanks a lot @abhishekaich27 for your solution, appreciate :)
