### ISSUE TITLE
Where can I download the model checkpoint?

### ISSUE THREAD

**Issue by zxqing01** [NiccoloCavagnero/PEM#4]
MODEL.WEIGHTS /path/to/checkpoint_file Where can I download the model checkpoint?

**Comment by Gabrysse** [comment]
Hi @z2587721154, we do not provide model checkpoint, you have to train the model yourself.

**Comment by zxqing01** [comment]
I use the checkpoint of 19999 times, why is the mIoU of the result only 75.0, which is so different from your 79.9, is 19999 times the final checkpoint, and is it the final checkpoint of running the 19999c as a test?
