### ISSUE TITLE
final checkpoint

### ISSUE THREAD

**Issue by zxqing01** [NiccoloCavagnero/PEM#6]
I use the checkpoint of 19999 times, why is the mIoU of the result only 75.0, which is so different from your 79.9, is 19999 times the final checkpoint, and is it the final checkpoint of running the 19999c as a test?

**Comment by Gabrysse** [comment]
Hi @z2587721154, what do you mean by "19999 times"? If you are referring to the checkpoint at 19999 iterations, the results may be consistent since the model has to be trained for a total of 80k iterations for cityscapes and a total of 160k iterations for ade20k.

**Comment by zxqing01** [comment]
The final checkpoint used, 89,999 iterative training sessions were performed, and the result was 77.9, which is also a certain gap with 79.9.Why, do I need to increase the number of trainings?

**Comment by zxqing01** [comment]
![Uploading 91a0fe170f1e1aee7ac5dfec42fb35f.png…]()

**Comment by zxqing01** [comment]
Sorry, I trained again to achieve the experimental results of the paper, thank you for your contribution, and I would like to ask you for another paper The revenge of BiSeNet: Efficient Multi-Task Image Segmentation, can you please share your source code, I adore you and have been following in your footsteps, the following is my email 2587721154@qq.com, thank you.

**Comment by Gabrysse** [comment]
Currently, we have no plans to release the code for the paper "The Revenge of BiSeNet: Efficient Multi-Task Image Segmentation". Check my github for updates in the following months ;)
